logo:
  icon: /images/avatar.png
  title: Mahoo Blog
  subtitle: "每个人的独立博客 | Designed by xaoxuu"
menubar:
  columns: 4
  items:
    - id: post
      theme: "#1BCDFC"
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: notebooks
      theme: "#3DC550"
      icon: solar:notebook-bookmark-bold-duotone
      title: 笔记本
      url: /notebooks/
    - id: explore
      theme: "#FA6400"
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/
    - id: social
      theme: "#F44336"
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/

site_tree:
  home:
    sidebar: starter, welcome, recent
  index_blog:
    sidebar: starter, welcome, recent
  index_topic:
    menu_id: topic
  topic:
    menu_id: topic
  my_goods:
    menu_id: my_goods
    rightbar: goods_toc

# 自定义首页
index_generator:
  custom: index.md # 自定义首页文件路径（相对于 source 目录）
  list_path: recent # 自定义首页列表路径（相对于 source 目录）

article:
  share: [wechat, weibo, email, link]

style:
  border-radius:
    bar: 4px
    card: 4px
    block: 4px
# comments:
#   service: artalk
#   artalk:
#     css: https://unpkg.com/artalk@2.7/dist/Artalk.css
#     js: https://unpkg.com/artalk@2.7/dist/Artalk.js
#     server: https://api.mahoo12138.cn/artalk/
#     placeholder: ''
#     darkMode: auto
